# fly.toml app configuration file generated for todo-list-delicate-field-2232 on 2025-04-27T07:10:49-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'todo-list-delicate-field-2232'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
