[tool.black]
line-length = 80
target-version = ['py312']
exclude = '''
/(
  | venv
  | build
  | dist
  | \.mypy_cache
  | \.pytest_cache
)/
'''

[tool.pytest.ini_options]
pythonpath = "src"
addopts = "--cov=src --cov-report=term-missing"
